### ISSUE TITLE
Create lexer to tokenize source file

### ISSUE THREAD

**Issue by tirth132** [tirth132/dino#1]
Task: Create lexer to that converts source file to tokens.

# Description
Create a lexer which reads source file and finds tokens and give us token as `Token` objects. Lexer will not
parse whole file when initialized, but it will read file ahead to find tokens when we will ask it for more tokens.
It must keep trace of line numbers and row number on line. They will be advanced when lexer will get next token.
`Token` objects shoud store type of token and value of that token. We must be able to know if there are more tokens
or not. It should throw an exception if there is no more tokens available to return.

# Task list
- [ ] A class called `DinoLexer` must be found inside package `com.dino.compiler`.
- [ ] Class must have a constructor which initializes lexer with file object.
- [ ] Lexer must store line number and row number. (Write getters for both)
- [ ] Write a method `hasMoreTokens()` to check if more tokens are available.
- [ ] Write a method `nextToken()` which returns next token as `Token` object.
- [ ] Method `nextToken()` must throw an exception if no more token is available.

Write test cases that tests all conditions mentioned.
